# Define action tags here

defaults: &defaults
  docker:
    - image: google/cloud-sdk:latest #circleci/buildpack-deps:xenial-scm
  working_directory: ~/chip-seq-pipeline2

python_defaults: &python_defaults
  docker:
    - image: quay.io/encode-dcc/chip-seq-pipeline:${CIRCLE_BRANCH}_${CIRCLE_WORKFLOW_ID}
  working_directory: ~/chip-seq-pipeline2

machine_defaults: &machine_defaults
  machine: 
    image: circleci/classic:latest
  working_directory: ~/chip-seq-pipeline2

make_tag: &make_tag
  name: make docker image tag
  command: |
    echo "export TAG=quay.io/encode-dcc/chip-seq-pipeline:${CIRCLE_BRANCH}_${CIRCLE_WORKFLOW_ID}" > ${BASH_ENV}
    echo "export TAG_DOCKERHUB=encodedcc/chip-seq-pipeline:${CIRCLE_BRANCH}_${CIRCLE_WORKFLOW_ID}" >> ${BASH_ENV}

install_singularity: &install_singularity
  name: install singularity
  command: |
    sudo apt-get update
    sudo apt-get install \
    python \
    dh-autoreconf \
    build-essential \
    libarchive-dev \
    squashfs-tools
    wget https://github.com/singularityware/singularity/releases/download/2.6.0/singularity-2.6.0.tar.gz
    tar xvf singularity-2.6.0.tar.gz
    cd singularity-2.6.0
    ./configure --prefix=/usr/local --sysconfdir=/etc
    make
    sudo make install
    singularity --version

# Define jobs here
version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run: *make_tag
      - run:
          name: build image
          command: |
            source ${BASH_ENV}
            export DOCKER_CACHE_TAG=dev-v1.3.5.1
            echo "pulling ${DOCKER_CACHE_TAG}!"
            docker pull quay.io/encode-dcc/chip-seq-pipeline:${DOCKER_CACHE_TAG}
            docker login -u=${QUAY_ROBOT_USER} -p=${QUAY_ROBOT_USER_TOKEN} quay.io
            docker build --cache-from quay.io/encode-dcc/chip-seq-pipeline:${DOCKER_CACHE_TAG} --build-arg GIT_COMMIT_HASH=${CIRCLE_SHA1} --build-arg BRANCH=${CIRCLE_BRANCH} --build-arg BUILD_TAG=${TAG} -t $TAG -f dev/docker_image/Dockerfile .
            docker push ${TAG}
            #docker push ${TAG_DOCKERHUB}
            docker logout
  test_tasks:
    <<: *machine_defaults
    steps:
      - checkout
      - run: *make_tag
      - run:
          no_output_timeout: 300m
          command: |
            source ${BASH_ENV}
            cd dev/test/test_task/
            rm -rf chip-seq-pipeline-test-data
            export BOTO_CONFIG=/dev/null
            gsutil -m cp -r gs://encode-pipeline-test-samples/encode-chip-seq-pipeline/chip-seq-pipeline-test-data .
            for wdl in test_*.wdl
            do
              json=${wdl%.*}.json
              result=${wdl%.*}.result.json
              ./test.sh ${wdl} ${json} ${TAG}
              if [[ $(wc -l "${result}" | awk '{print $1}') > 1 ]]; then
                python -c "import sys; import json; data=json.loads(sys.stdin.read()); sys.exit(int(not data[u'match_overall']))" < ${result}
              fi
              rm -f ${result}
            done
            
  test_workflow_se:
    <<: *machine_defaults
    steps:
      - checkout
      - run: *make_tag
      - run:
          no_output_timeout: 300m
          command: |
            source ${BASH_ENV}
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            cd dev/test/test_workflow/
            echo ${GCLOUD_SERVICE_ACCOUNT_SECRET_JSON} > tmp_key.json
            ./test_chip.sh ENCSR000DYI_subsampled_chr19_only.json tmp_key.json ${TAG}
            python -c "import sys; import json; data=json.loads(sys.stdin.read()); sys.exit(int(not data[u'outputs'][u'chip.qc_json_ref_match']))" < ENCSR000DYI_subsampled_chr19_only.metadata.json

  test_workflow_ctl_sub_se:
    <<: *machine_defaults
    steps:
      - checkout
      - run: *make_tag
      - run:
          no_output_timeout: 300m
          command: |
            source ${BASH_ENV}
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            cd dev/test/test_workflow/
            echo ${GCLOUD_SERVICE_ACCOUNT_SECRET_JSON} > tmp_key.json
            ./test_chip.sh ENCSR000DYI_subsampled_ctl_sub_chr19_only.json tmp_key.json ${TAG}
            python -c "import sys; import json; data=json.loads(sys.stdin.read()); sys.exit(int(not data[u'outputs'][u'chip.qc_json_ref_match']))" < ENCSR000DYI_subsampled_ctl_sub_chr19_only.metadata.json

  test_workflow_unrep_se:
    <<: *machine_defaults
    steps:
      - checkout
      - run: *make_tag
      - run:
          no_output_timeout: 300m
          command: |
            source ${BASH_ENV}
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            cd dev/test/test_workflow/
            echo ${GCLOUD_SERVICE_ACCOUNT_SECRET_JSON} > tmp_key.json
            ./test_chip.sh ENCSR000DYI_subsampled_chr19_only_unrep.json tmp_key.json ${TAG}
            python -c "import sys; import json; data=json.loads(sys.stdin.read()); sys.exit(int(not data[u'outputs'][u'chip.qc_json_ref_match']))" < ENCSR000DYI_subsampled_chr19_only_unrep.metadata.json

  test_workflow_pe:
    <<: *machine_defaults
    steps:
      - checkout
      - run: *make_tag
      - run:
          no_output_timeout: 300m
          command: |
            source ${BASH_ENV}
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            cd dev/test/test_workflow/
            echo ${GCLOUD_SERVICE_ACCOUNT_SECRET_JSON} > tmp_key.json
            ./test_chip.sh ENCSR936XTK_subsampled_chr19_only.json tmp_key.json ${TAG}
            python -c "import sys; import json; data=json.loads(sys.stdin.read()); sys.exit(int(not data[u'outputs'][u'chip.qc_json_ref_match']))" < ENCSR936XTK_subsampled_chr19_only.metadata.json

  test_workflow_ctl_sub_pe:
    <<: *machine_defaults
    steps:
      - checkout
      - run: *make_tag
      - run:
          no_output_timeout: 300m
          command: |
            source ${BASH_ENV}
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            cd dev/test/test_workflow/
            echo ${GCLOUD_SERVICE_ACCOUNT_SECRET_JSON} > tmp_key.json
            ./test_chip.sh ENCSR936XTK_subsampled_ctl_sub_chr19_only.json tmp_key.json ${TAG}
            python -c "import sys; import json; data=json.loads(sys.stdin.read()); sys.exit(int(not data[u'outputs'][u'chip.qc_json_ref_match']))" < ENCSR936XTK_subsampled_ctl_sub_chr19_only.metadata.json

  test_workflow_ctl_sub_1ctl_pe:
    <<: *machine_defaults
    steps:
      - checkout
      - run: *make_tag
      - run:
          no_output_timeout: 300m
          command: |
            source ${BASH_ENV}
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            cd dev/test/test_workflow/
            echo ${GCLOUD_SERVICE_ACCOUNT_SECRET_JSON} > tmp_key.json
            ./test_chip.sh ENCSR936XTK_subsampled_ctl_sub_1ctl_chr19_only.json tmp_key.json ${TAG}
            python -c "import sys; import json; data=json.loads(sys.stdin.read()); sys.exit(int(not data[u'outputs'][u'chip.qc_json_ref_match']))" < ENCSR936XTK_subsampled_ctl_sub_1ctl_chr19_only.metadata.json

  test_workflow_hist_se:
    <<: *machine_defaults
    steps:
      - checkout
      - run: *make_tag
      - run:
          no_output_timeout: 300m
          command: |
            source ${BASH_ENV}
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            cd dev/test/test_workflow/
            echo ${GCLOUD_SERVICE_ACCOUNT_SECRET_JSON} > tmp_key.json
            ./test_chip.sh ENCSR000DYI_subsampled_chr19_only_hist.json tmp_key.json ${TAG}
            python -c "import sys; import json; data=json.loads(sys.stdin.read()); sys.exit(int(not data[u'outputs'][u'chip.qc_json_ref_match']))" < ENCSR000DYI_subsampled_chr19_only_hist.metadata.json

  test_workflow_hist_unrep_se:
    <<: *machine_defaults
    steps:
      - checkout
      - run: *make_tag
      - run:
          no_output_timeout: 300m
          command: |
            source ${BASH_ENV}
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            cd dev/test/test_workflow/
            echo ${GCLOUD_SERVICE_ACCOUNT_SECRET_JSON} > tmp_key.json
            ./test_chip.sh ENCSR000DYI_subsampled_chr19_only_hist_unrep.json tmp_key.json ${TAG}
            python -c "import sys; import json; data=json.loads(sys.stdin.read()); sys.exit(int(not data[u'outputs'][u'chip.qc_json_ref_match']))" < ENCSR000DYI_subsampled_chr19_only_hist_unrep.metadata.json

  test_workflow_hist_pe:
    <<: *machine_defaults
    steps:
      - checkout
      - run: *make_tag
      - run:
          no_output_timeout: 300m
          command: |
            source ${BASH_ENV}
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            cd dev/test/test_workflow/
            echo ${GCLOUD_SERVICE_ACCOUNT_SECRET_JSON} > tmp_key.json
            ./test_chip.sh ENCSR936XTK_subsampled_chr19_only_hist.json tmp_key.json ${TAG}
            python -c "import sys; import json; data=json.loads(sys.stdin.read()); sys.exit(int(not data[u'outputs'][u'chip.qc_json_ref_match']))" < ENCSR936XTK_subsampled_chr19_only_hist.metadata.json


# Define workflow here
workflows:
  version: 2
  build_workflow:
    jobs:
      - build
      - test_tasks:
          requires:
            - build
      - test_workflow_se:
          requires:
            - build
      - test_workflow_ctl_sub_se:
          requires:
            - build
      - test_workflow_unrep_se:
          requires:
            - build
      - test_workflow_pe:
          requires:
            - build
      - test_workflow_ctl_sub_pe:
          requires:
            - build
      - test_workflow_ctl_sub_1ctl_pe:
          requires:
            - build
      - test_workflow_hist_se:
          requires:
            - build
      - test_workflow_hist_unrep_se:
          requires:
            - build
      - test_workflow_hist_pe:
          requires:
            - build
